# Server Monitoring Made Easy Configuration Example

# Global logging configuration
logging:
  level: "info" # Global logging level (debug, info, warning, error)
  # Component-specific logging levels (optional)
  components:
    monitors: "info"
    alerts: "warning"
    metrics: "warning"
    daemon: "info"

# File paths configuration
paths:
  # Log file path - ensure this directory exists and has proper permissions
  # For non-root users, consider using: ~/.local/log/sme/server-monitor.log
  log_file: "~/.local/log/sme/server-monitor.log"

  # PID file path - ensure this directory exists and has proper permissions
  # For non-root users, consider using: ~/.local/run/sme/server-monitor.pid
  pid_file: "~/.local/run/sme/server-monitor.pid"

# Monitor configuration
monitors:
  cpu:
    enabled: true
    interval: 60 # seconds
    threshold: 80 # percentage
    alert_count: 3 # number of consecutive threshold breaches before alerting

  memory:
    enabled: true
    interval: 60
    threshold: 80
    alert_count: 1

  disk:
    enabled: true
    interval: 300
    threshold: 85
    alert_count: 2
    path: "/" # mount point to monitor

  ping:
    enabled: true
    interval: 60
    threshold: 200 # milliseconds
    alert_count: 5
    targets: # list of hosts to ping
      - "8.8.8.8"
      - "1.1.1.1"
      - "google.com"

# Alert configuration
alerts:
  enabled: true
  methods:
    - type: "console" # Built-in console alerts
      enabled: true

    # Uncomment and configure for email alerts
    # - type: "email"
    #   enabled: false
    #   smtp_server: "smtp.gmail.com"
    #   smtp_port: 587
    #   username: "your-email@gmail.com"
    #   password: "your-app-specific-password"
    #   from_addr: "your-email@gmail.com"
    #   to_addr: "recipient@example.com"

    # Uncomment and configure for Slack alerts
    # - type: "slack"
    #   enabled: false
    #   webhook_url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"

# Configure your notification channels here
notifications:
  # Discord example
  - type: discord
    uri: "discord://12345678901234567890/lakajd_0asjkadsljkdalksjdlakjw92w92929wksks"
    enabled: true

  # Slack example
  - type: slack
    uri: "slack://tokenA/tokenB/tokenC"
    enabled: false

  # Telegram example
  - type: telegram
    uri: "tgram://bottoken/ChatID"
    enabled: false
