# Server Monitoring Made Easy Configuration

monitors:
  cpu:
    enabled: true
    threshold: 80 # Alert when CPU usage > 80%
    interval: 60 # Check every 60 seconds
    alert_count: 3 # Alert after 3 consecutive failures

  memory:
    enabled: true
    threshold: 80 # Alert when memory usage > 90%
    interval: 60
    alert_count: 1 # Alert after 3 consecutive failures

  disk:
    enabled: true
    threshold: 85 # Alert when disk is > 85% full
    interval: 300 # Check every 5 minutes
    path: "/" # Monitor root partition
    alert_count: 2 # Alert after 2 consecutive failures (less for disk since it's checked less frequently)

  ping:
    enabled: true
    threshold: 200 # Alert when ping > 200ms
    interval: 60
    alert_count: 5 # More consecutive checks for network latency due to potential fluctuations
    targets:
      - "8.8.8.8" # Google DNS
      - "1.1.1.1" # Cloudflare DNS
      - "google.com" # Google
    timeout: 5 # Ping timeout in seconds

# Configure your notification channels here
notifications:
  # Discord example
  - type: discord
    uri: "discord://12345678901234567890/lakajd_0asjkadsljkdalksjdlakjw92w92929wksks"
    enabled: true

  # Slack example
  - type: slack
    uri: "slack://tokenA/tokenB/tokenC"
    enabled: false

  # Telegram example
  - type: telegram
    uri: "tgram://bottoken/ChatID"
    enabled: false

logging:
  level: "info" # Global log level: debug, info, warning, error
  file: "stdout" # Use 'stdout' for console output or a file path
  components: # Per-component log levels
    monitors: "info" # Log level for monitors
    alerts: "info" # Log level for alert system
    metrics: "error" # Log level for metrics command (suppress most output)
    daemon: "info" # Log level for daemon operations
