# This compose file is compatible with both Docker and Podman
---
services:
  monitor:
    build: .
    volumes:
      - ./config.yaml:/home/sme/config.yaml:ro
      - ./data:/home/sme/data
      - ./logs:/home/sme/logs
      - ./run:/home/sme/run
      - /proc:/host/proc:ro # Mount host's proc directory read-only
    pid: "host" # Needed for accurate system metrics
    privileged: true # Needed for system metrics access
    network_mode: "host" # Needed for accurate network metrics
    restart: unless-stopped
    cap_add:
      - NET_RAW # Needed for ping
      - NET_ADMIN # Needed for network operations
    container_name: "sme"
    user: "${SME_UID:-999}:${SME_GID:-999}" # Allow override of user/group ID
    environment:
      - CONTAINER=1
      - PYTHONUNBUFFERED=1
      - LOGLEVEL=debug
