# This compose file is compatible with both Docker and Podman
---
services:
  monitor:
    build: .
    volumes:
      - ./config.yaml:/etc/sme/config.yaml:ro
      - ./logs:/var/log/sme
    tmpfs:
      - /var/run/sme # Simple tmpfs mount compatible with both Docker and Podman
    pid: "host" # Needed for accurate system metrics
    privileged: true # Needed for system metrics access
    network_mode: "host" # Needed for accurate network metrics
    restart: unless-stopped
    cap_add:
      - NET_RAW # Needed for ping
      - NET_ADMIN # Needed for network operations
    container_name: "sme"
    user: "999:999" # Set container user/group ID for proper permissions
